# Generated by Django 5.0.1 on 2024-01-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('roll', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
