# Generated by Django 5.0.1 on 2024-01-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='roll',
            new_name='enr',
        ),
    ]
