# Generated by Django 5.0.1 on 2024-01-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_roll_students_enr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='marks',
            field=models.FloatField(),
        ),
    ]
