# Generated by Django 5.0.1 on 2024-01-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_students_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
    ]
