# Generated by Django 5.0.1 on 2024-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_students_marks_students_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
