# Generated by Django 5.0.1 on 2024-01-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_students_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
