# Generated by Django 5.0.1 on 2024-01-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_students_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='task',
            field=models.TextField(default='None'),
        ),
    ]
