# Generated by Django 5.0.1 on 2024-01-31 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_students_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='StudentsModel',
        ),
    ]
